trace:
  # endpoint: http://127.0.0.1:14268/api/traces
  endpoint:
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 10s
data:
  database:
    # driver: mysql
    # source: root:password@tcp(127.0.0.1:3306)/testdb?parseTime=True
    driver: sqlite3
    source: file:demo.db?mode=memory&cache=shared&_fk=1
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 5s
    read_timeout: 5s
    write_timeout: 10s
    